const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"报修类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBaoxiu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公寓类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"留言类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"调宿申请类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryTiaosushenqing"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"学院管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueyuan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"专业管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhuanye"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"访客管理",
                        "menuJump":"列表",
                        "tableName":"fangke"
                    }
                ],
                "menu":"访客管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公寓管理",
                        "menuJump":"列表",
                        "tableName":"fangwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"公寓收藏管理",
                        "menuJump":"列表",
                        "tableName":"fangwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "导入导出",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公寓学生管理",
                        "menuJump":"列表",
                        "tableName":"fangwuRuzhu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公寓退宿申请管理",
                        "menuJump":"列表",
                        "tableName":"fangwuTuisu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公寓入住申请管理",
                        "menuJump":"列表",
                        "tableName":"fangwuYuyue"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "审核",
                            "修改",
                            "删除"
                        ],
                        "menu":"调宿申请管理",
                        "menuJump":"列表",
                        "tableName":"tiaosushenqing"
                    }
                ],
                "menu":"公寓管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"缴费管理",
                        "menuJump":"列表",
                        "tableName":"jiaofei"
                    }
                ],
                "menu":"缴费管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"报修管理",
                        "menuJump":"列表",
                        "tableName":"baoxiu"
                    }
                ],
                "menu":"报修管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"卫生管理",
                        "menuJump":"列表",
                        "tableName":"weisheng"
                    }
                ],
                "menu":"卫生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "添加考题",
                            "删除"
                        ],
                        "menu":"试卷管理",
                        "menuJump":"列表",
                        "tableName":"exampaper"
                    }
                ],
                "menu":"试卷管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"试题管理",
                        "menuJump":"列表",
                        "tableName":"examquestion"
                    }
                ],
                "menu":"试题管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"测试记录",
                        "menuJump":"列表",
                        "tableName":"examrecord"
                    }
                ],
                "menu":"考试管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍管理员管理",
                        "menuJump":"列表",
                        "tableName":"susheguanliyuan"
                    }
                ],
                "menu":"宿舍管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
    ,
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"访客管理",
                                "menuJump":"列表",
                                "tableName":"fangke"
                            }
                        ],
                        "menu":"访客管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"公寓管理",
                                "menuJump":"列表",
                                "tableName":"fangwu"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"公寓学生管理",
                                "menuJump":"列表",
                                "tableName":"fangwuRuzhu"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "审核"
                                ],
                                "menu":"公寓退宿申请管理",
                                "menuJump":"列表",
                                "tableName":"fangwuTuisu"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "审核"
                                ],
                                "menu":"公寓入住申请管理",
                                "menuJump":"列表",
                                "tableName":"fangwuYuyue"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "审核"
                                ],
                                "menu":"调宿申请管理",
                                "menuJump":"列表",
                                "tableName":"tiaosushenqing"
                            }
                        ],
                        "menu":"公寓管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除"
                                ],
                                "menu":"缴费管理",
                                "menuJump":"列表",
                                "tableName":"jiaofei"
                            }
                        ],
                        "menu":"缴费管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"留言管理",
                                "menuJump":"列表",
                                "tableName":"liuyan"
                            }
                        ],
                        "menu":"留言管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"报修管理",
                                "menuJump":"列表",
                                "tableName":"baoxiu"
                            }
                        ],
                        "menu":"报修管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除"
                                ],
                                "menu":"卫生管理",
                                "menuJump":"列表",
                                "tableName":"weisheng"
                            }
                        ],
                        "menu":"卫生管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"测试记录",
                                "menuJump":"列表",
                                "tableName":"examrecord"
                            }
                        ],
                        "menu":"考试管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"学生管理",
                                "menuJump":"列表",
                                "tableName":"yonghu"
                            }
                        ],
                        "menu":"学生管理"
                    }
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"宿舍管理员",
                "tableName":"susheguanliyuan"
            }
]
    }
}
export default menu;
